### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by joemarlo** [priism-center/shinyQuiz#1]
FEATURE LIST
- [x] mvp
  - [x] Easy-mode pre-generated question structure @gperrett
  - [x] Sandbox-mode that has quasi-infinite questions
    - [x] Function that randomly generates questions @gperrett 

- [ ] wishlist
  - [ ] ~Print-out grade report -- html and pdf version~
  - [ ] ~Google Sheets write out results~
  - [ ] Rmarkdown / quarto support
  - [ ] Styling themes
  - [ ] Different layouts
  - [ ] On final menu, hover over row to preview question 
  - [ ] Pipeable quiz object for easy modification
  - [ ] Make quiz object modifiable so quiz can be adjusted on-the-fly within Shiny?
  - [x] Make question header ("practice what you've learned") editable from `set_quiz_options()`

<br>

KNOWN BUGS
  - [x] Make green check / red X compatible with `set_quiz_options(include_question_title = TRUE)`

<br>

QUIZ WRITER API @gperrett 
- [x] Create a user friendly API that can create questions and output as HTML
- [x] Output should be HTML for question, function for grader, function for user answer printer, correct answer printer 
- [x] Create a preview that spins up a shiny app to test in RStudio 
  - [x] Create preview that shows only html, no interactivity
- [x] Create method of generating infinite questions 

<br>

STATE MACHINE / CORE LOGIC @joemarlo 
- [x] Create test quiz
- [x] S4 classes for quiz, quiz questions
- [x] Sandbox mode vs end early mode
- [x] Constructors that interface between the user-friendly code and the backend
- [x] Need function that takes in raw HTML
- [x] Move messages into an object
- [x] BUG: shows quiz skipped when getting one wrong (not in sandbox mode)
- [x] Add option to make 'end early' mode optional

<br>

SHINY INTEGRATION @joemarlo 
- [x] How to make this play nicely with Shiny
- [x] How is the namespace handled
  - [x] Change `id`, `id_parent` args to `ns`
- [ ] ~Add style sheets~
- [ ] Convert to input/output paradigm? https://book.javascript-for-r.com/shiny-output.html

<br>

TACTICAL
- [x] Move over code from thinkCausal repo @joemarlo 
- [x] Structure as an R package @joemarlo 
- [x] Move repo to PRIISM @joemarlo 
- [x] Move current thinkCausal quizzes to shinyQuiz structure
- [x] Unit tests: how to test preview functions; write state machine tests
- [x] Examples
- [x] Review need for `\dontrun{}`
- [x] Add example app running on shinyapps.io
- [x] Review docs: all functions generally need more thorough explanations
- [x] Review vignettes
- [x] CRAN: pass check on linux, mac, windows and review [checklist](https://cran.r-project.org/web/packages/submission_checklist.html) 
- [x] Review DESCRIPTION
